# asset-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-service
  template:
    metadata:
      labels:
        app: asset-service
    spec:
      containers:
        - name: asset-service
          image: asset-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: '5001'
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: intania-overflow-config
                  key: JWT_SECRET
