version: "3.8"

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: replies
        networks:
            - intania-overflow-network

    asset-service:
        build: ./asset-service
        container_name: asset-service
        expose:
            - "3000"

    # thread-service:
    #     build:
    #         context: ./
    #         dockerfile: ./thread-service/Dockerfile
    #     container_name: thread-service
    #     expose:
    #         - "30043"
    #     ports:
    #         - "30043:30043"
    #     networks:
    #         - intania-overflow-network

    reply-service:
        build: ./reply-service
        container_name: reply-service
        expose:
            - "5000"
        ports:
            - "5000:5000"
        environment:
            MONGO_URI: mongodb://mongodb:27017/replies
        depends_on:
            - mongodb
        networks:
            - intania-overflow-network

    # voting-service:
    #     build: 
    #         context: ./
    #         dockerfile: ./voting-service/Dockerfile
    #     expose:
    #         - "3000"
    #     ports:
    #         - "3000:3000"
    #     networks:
    #         - intania-overflow-network

    # rabbitmq:
    #     image: rabbitmq:4.0-management
    #     container_name: rabbitmq
    #     ports:
    #         - "5672:5672"
    #         - "15672:15672"
    #     restart: always
    #     networks:
    #         - intania-overflow-network

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: yourusername
            POSTGRES_PASSWORD: yourpassword
            POSTGRES_DB: userdatabase
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        networks:
            - intania-overflow-network

    user-service:
        build: 
            context: ./
            dockerfile: ./user-service/Dockerfile
        container_name: user-service
        expose:
            - "50051"
        ports:
            - "50051:50051"
        depends_on:
            - postgres
        networks:
            - intania-overflow-network
        environment:
            DATABASE_URL: "postgresql://yourusername:yourpassword@postgres:5432/userdatabase"

networks:
    intania-overflow-network:
        driver: bridge