version: "3.8"

services:
    asset-service:
        build: ./asset-service
        container_name: asset-service
        expose:
            - "3000"

    thread-service:
        build:
            context: ./
            dockerfile: ./thread-service/Dockerfile
        container_name: thread-service
        expose:
            - "30043"
        ports:
            - "30043:30043"
        networks:
            - intania-overflow-network

    voting-service:
        build: 
            context: ./
            dockerfile: ./voting-service/Dockerfile
        expose:
            - "3000"
        ports:
            - "3000:3000"
        networks:
            - intania-overflow-network

    # rabbitmq:
    #     image: rabbitmq:4.0-management
    #     container_name: rabbitmq
    #     ports:
    #         - "5672:5672"
    #         - "15672:15672"
    #     restart: always
    #     networks:
    #         - intania-overflow-network

networks:
    intania-overflow-network:
        driver: bridge
